----------------Usuwanie tabel ------------------
DROP TABLE ADRESY CASCADE CONSTRAINTS;
DROP TABLE KIERUNKI CASCADE CONSTRAINTS;
DROP TABLE STANOWISKA CASCADE CONSTRAINTS;
DROP TABLE WYDZIALY CASCADE CONSTRAINTS;
DROP TABLE PRACOWNICY CASCADE CONSTRAINTS;
DROP TABLE AKADEMIKI CASCADE CONSTRAINTS;
DROP TABLE OCENY CASCADE CONSTRAINTS;
DROP TABLE PRACE_DYPLOMOWE CASCADE CONSTRAINTS;
DROP TABLE STUDENCI CASCADE CONSTRAINTS;
DROP TABLE PRZEDMIOTY CASCADE CONSTRAINTS;